info:
  status: OK
  
spring:
  application:
    name: JavaService  
  
server:
  port: 8081
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      